pipeline {
    agent any

    stages {
        stage ('Git') {
            steps {
                dir ('CRM') {
                    checkout([$class: 'GitSCM', branches: [[name: env.GitBranch]],
                        extensions: [[$class: 'CloneOption', timeout: 45]],
                        userRemoteConfigs: [[url: 'ssh://gitblit.saritasa.com/anton/crm-dotnet.git']]])
                }
            }
        }

        stage ('Build SaritasaApi') {
            steps {
                echo '.'
            }
        }

        stage ('Publish Installer') {
            steps {
                bat script: 'docker-compose run --rm installer'
            }
        }
    }
}